format = """
[](#875f87)\
$os\
$username\
[](bg:#5f5f87 fg:#875f87)\
$directory\
[](fg:#5f5f87 bg:#875f87)\
$git_branch\
$git_status\
[](fg:#875f87 bg:#875f87)\
$time\
[ ](fg:#875f87)\
"""

right_format = """
[](#875f87)
$status
"""

# Disable the blank line at the start of the prompt
# add_newline = false

[username]
show_always = true
style_user = "bg:#875f87"
style_root = "bg:#875f87"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:#875f87"
disabled = true # Disabled by default

[directory]
style = "bg:#5f5f87"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#875f87"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#5f5f87"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#5f5f87"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#875f87"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#875f87"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#875f87"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#5f5f87"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#875f87"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#5f5f87"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#875f87"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#5f5f87"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#875f87"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#5f5f87"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#875f87"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#5f5f87"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#875f87"
format = '[ $time ]($style)'

[status]
disabled = false
style =  "bg:#875f87"
map_symbol = false
symbol = ""
success_symbol = ""
format = "[$symbol $status]($style)"
