return {
  "nvim-treesitter/nvim-treesitter",
  branch = "main",
  -- Recommended by docs. See https://github.com/nvim-treesitter/nvim-treesitter/tree/main#installation
  lazy = false,
  build = ":TSUpdate",
  opts = {
    ensure_installed = {
      "vim",
      "lua",
      "vimdoc",
      "html",
      "css",
      "markdown",
      "markdown_inline",
      "rust",
      "yaml",
      "c_sharp",
      "javascript",
      "typescript",
      "tsx",
      "go",
      "c",
      "cpp",
      "bash",
      "python",
      "haskell",
      "astro",
      "bicep",
    },
  },
}
